spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Noah John - Developer in qa mode"
    email: "noah@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345