server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active:
      - "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  datasource:
##    url: jdbc:mysql://localhost:3309/cardsdb
#    url: jdbc:mysql://localhost:3306/cardsdb
#    username: root
##    password: root
#    password: redDEVILS1.
#  jpa:
#    show-sql: true
#  sql:
#    init:
#      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

#actuator related configurations
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

# Eureka related configurations
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# The info that is displayed in the eureka dashboard
info:
  app:
    name: "cards"
    description: "Eazy Pay Cards Microservice"
    version: "1.0.0"



